[general]
import = [ "~/.config/alacritty-theme/themes/ayu_dark_rev.toml" ]

[font]
size = 13

[font.normal]
family = "PragmataPro Mono"
style = "Regular"

[font.italic]
family = "PragmataPro Mono"
style = "Italic"

[font.bold]
family = "PragmataPro Mono"
style = "Bold"

[font.bold_italic]
family = "PragmataPro Mono"
style = "Bold Italic"

[window]
dimensions = { columns = 80, lines = 30 }
dynamic_padding = true
option_as_alt = "OnlyLeft"
padding = { x = 12, y = 12 }

[[keyboard.bindings]]
mods = "Command"
key = "N"
action = "SpawnNewInstance"
