[general]
import = [ "~/.config/alacritty-theme/themes/dark_plus.toml" ]

[font]
normal      = { family = "Pragmata", style = "Regular" }
italic      = { family = "Pragmata", style = "Italic" }
bold        = { family = "Pragmata", style = "Bold" }
bold_italic = { family = "Pragmata", style = "Bold Italic" }
size        = 14

[window]
dimensions      = { columns = 90, lines = 40 }
dynamic_padding = true
option_as_alt   = "OnlyLeft"
padding         = { x = 16, y = 16 }
