[general]
import = [ "~/.config/alacritty-theme/themes/one_dark.toml" ]

[font]
size = 14

[font.normal]
family = "Pragmata"
style = "Regular"

[font.italic]
family = "Pragmata"
style = "Italic"

[font.bold]
family = "Pragmata"
style = "Bold"

[font.bold_italic]
family = "Pragmata"
style = "Bold Italic"

[window]
dimensions      = { columns = 90, lines = 40 }
dynamic_padding = true
option_as_alt   = "OnlyLeft"
padding         = { x = 16, y = 16 }
