[general]
import = [ "~/.config/alacritty-theme/themes/everforest_light.toml" ]

[font]
size = 14

[font.normal]
family = "Pragmata"
style = "Regular"

[font.italic]
family = "Pragmata"
style = "Italic"

[font.bold]
family = "Pragmata"
style = "Bold"

[font.bold_italic]
family = "Pragmata"
style = "Bold Italic"

[window]
dimensions = { columns = 80, lines = 30 }
dynamic_padding = true
option_as_alt = "OnlyLeft"
padding = { x = 16, y = 16 }

[[keyboard.bindings]]
mods = "Command"
key = "N"
action = "SpawnNewInstance"
