theme = "onedark"

[editor]
line-number = "relative"
true-color = true
bufferline = "multiple"
color-modes = true
rulers = [80, 100, 120]

[editor.file-picker]
git-ignore = false

[editor.soft-wrap]
enable = true
