theme = "gruvbox"

[editor]
line-number = "relative"
true-color = true
bufferline = "multiple"
color-modes = true
scrolloff = 99

[editor.file-picker]
git-ignore = false

[editor.soft-wrap]
enable = true

[keys.normal]
X = "extend_line_above"
