theme = "elora"

[editor]
line-number = "relative"
true-color = true
bufferline = "multiple"
color-modes = true
# rulers = [80, 100, 120]
# cursorline = true
# cursorcolumn = true

[editor.file-picker]
git-ignore = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.normal]
V = "select_mode"
v = ["collapse_selection", "select_mode"]
ret = "repeat_last_motion"
m.c = "@ms`"
m.e = "@ms_"
m.b = "@ms*ms*"
"\\" = "@mips[,\\.;:\\)] <ret>li<ret><esc>,"

[keys.select]
ret = "repeat_last_motion"
m.c = "@ms`"
m.e = "@ms_"
m.b = "@ms*ms*"
