[[language]]
name = "markdown"
language-servers = ["marksman"]

[[language]]
name = "latex"
language-servers = ["texlab", "ltex-ls-plus"]

[[language]]
name = "html"
auto-format = false

[language-server.ltex-ls-plus]
command = "ltex-ls-plus"

[language-server.ltex-ls-plus.config.ltex]
language = "en-CA"

[language-server.texlab]
command = "texlab"

[language-server.texlab.config.texlab]
diagnosticsDelay = 500

[language-server.texlab.config.texlab.build]
executable = "latexmk"
args = ["-pdf", "-interaction=nonstopmode", "-synctex=1", "%f"]
onSave = true

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true
onEdit = true

[language-server.texlab.config.texlab.diagnostics]
ignoredPatterns = [
  "overfull",
  "instead of",
]

[language-server.texlab.config.texlab.forwardSearch]
executable = "/Applications/Skim.app/Contents/SharedSupport/displayline"
args = ["-r", "%l", "%p", "%f"]

[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
exportPdf = "onSave"
formatterMode = "typstyle"
formatterPrintWidth = 120
completion.triggerOnSnippetPlaceholders = true

[[language]]
name = "typst"
language-servers = ["tinymist"]
