[[language]]
name = "html"
auto-format = false

## LaTeX

[[language]]
name = "latex"
language-servers = ["texlab", "ltex-ls-plus"]

[language-server.ltex-ls-plus]
command = "ltex-ls-plus"
config.ltex.language = "en-CA"

[language-server.texlab]
command = "texlab"

[language-server.texlab.config.texlab]
diagnosticsDelay = 500
diagnostics.ignoredPatterns = ["overfull", "instead of"]

[language-server.texlab.config.texlab.build]
executable = "latexmk"
args = ["-pdf", "-interaction=nonstopmode", "-synctex=1", "%f"]
onSave = true

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true
onEdit = true

[language-server.texlab.config.texlab.forwardSearch]
executable = "/Applications/Skim.app/Contents/SharedSupport/displayline"
args = ["-r", "%l", "%p", "%f"]

# Markdown

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }
# formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = false
language-servers = ["marksman"]

# Typst

[[language]]
name = "typst"
language-servers = ["tinymist"]

[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
exportPdf = "onDocumentHasTitle"
formatterMode = "typstyle"
completion.triggerOnSnippetPlaceholders = false

